title: ðŸš¢ xtripe ship log ðŸ‘
description: >-
  Things shipped by Stripe alumni
baseurl: ""
url: "https://xtripe.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  shipped:
    output: true
